### ISSUE TITLE
Is the readme and video outdated about nodemon?

### ISSUE THREAD

**Issue by sunshineo** [Microsoft/generator-docker#93]
I do not get a question "Do you want to use Nodemon" as the readme gif and video described.

**Comment by SteveLasker** [comment]
Yes, sorry sunshineo, We do need to update the animated gif as well. Please see the updated steps in the ReadMe.md for starting Node.js. Since we made the gif, we've added debug and release versions of the dockerfile and docker-compose files. The debug has nodemon and the release version doesn't. As with all our scaffolded code, you can change it afterwards. We felt the question wasn't needed as we believe we should assume nodemon in debug.  
So, is this the behavior you prefer, and we just need to update the animated gif? See #95
